language: node_js
node_js:
    - 8
cache: yarn
before_script:
    - if [ $TRAVIS_BRANCH = "master" ]; then NODE_ENV=production; else NODE_ENV=development; fi;
    - echo "On branch $TRAVIS_BRANCH"
    - echo "NODE_ENV=$NODE_ENV"
    - NODE_ENV=$NODE_ENV yarn build
script:
    - yarn test
deploy:
    provider: pages
    local_dir: dist/webpack-monitor
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    on:
        branch: master
